### ISSUE TITLE
可以支持json吗？

### ISSUE THREAD

**Issue by AdamvvYau** [China-Mr-zhong/Fast.Framework#1]
比如pojo有个些字段是动态的，添加个JSON属性后能组合保存到表的一个json的列中。

**Comment by China-Mr-zhong** [comment]
你好，很高兴你能提出需求，但我没有明白你的需求，能再详细说明一下吗？谢谢

**Comment by AdamvvYau** [comment]
比如A表有个ExtJson字段，保存的是一个json串，在对应的mode A中，有个字典对象的属性定义为json字段
class A{
   [JsonField]
    public Dictionary<string,object> ExtJson{get;set;}
}
操作model A的ExtJson时能更新到表A中，也能从表中查询这个json并返回这个字典。

**Comment by China-Mr-zhong** [comment]
现已支持Json序列化，请参考[README.md](https://github.com/China-Mr-zhong/Fast.Framework/blob/master/README.md)原生特性说明
